// Keeps the on-device deck in step with the one bundled in the app.

import * as db from './db.js';

/**
 * Fields the bundle owns. When the deck is corrected — a fixed gloss, a
 * stripped quote mark, a better translation — these are copied over the row
 * already on the device. Scheduling lives in the reviews store, keyed by the
 * row's id, so rewriting content never touches progress.
 */
const CONTENT_FIELDS = [
  'englishText', 'farsiText', 'finglish', 'literalGloss', 'difficulty',
  'situation', 'grammarTags', 'breakdown', 'alternatives',
  // A drill's own fields. Without them a corrected drill would reach the
  // device only if its Persian answer changed.
  'stem', 'stemEn', 'transform', 'cue', 'cueEn',
];

/**
 * Merge the bundled deck into IndexedDB.
 *
 * Three things the earlier version got wrong, each silently:
 * - it only ever added sentences, so a correction to one already on the device
 *   never arrived (the quote-mark fix to the word map, for one);
 * - it only copied a breakdown onto rows that had none, for the same reason;
 * - it never removed a sentence the deck had dropped.
 *
 * Rows are matched on the bundle's stable id first, then on the Persian text,
 * which is how rows created before the bundle carried ids are adopted. A
 * dropped sentence is removed only if it was never reviewed: one with history
 * stays, because deleting it would delete the history with it.
 *
 * Returns { added, updated, removed } for the caller to report.
 */
export async function syncBundled(incoming) {
  const [existing, reviews] = await Promise.all([
    db.getAll(db.STORE.sentences),
    db.getAll(db.STORE.reviews),
  ]);

  // Two indexes, and both only ever hold rows the bundle owns. A sentence you
  // added yourself must not be adoptable: match it by text and the next bundle
  // that happens to contain the same sentence would overwrite what you wrote.
  const bySeedId = new Map();
  const byText = new Map();
  for (const row of existing) {
    if (row.source !== 'seed') continue;
    if (row.seedId) bySeedId.set(row.seedId, row);
    // Rows created before seedId existed use the bundle id as their own.
    if (!bySeedId.has(row.id)) bySeedId.set(row.id, row);
    byText.set(row.farsiText, row);
  }

  const now = Date.now();
  const matched = new Set();
  const writes = [];
  let added = 0;
  let updated = 0;

  for (const source of incoming) {
    const row = (source.id && bySeedId.get(source.id)) ?? byText.get(source.farsiText);

    if (row && !matched.has(row.id)) {
      matched.add(row.id);
      const next = { ...row, seedId: source.id ?? row.seedId };
      for (const field of CONTENT_FIELDS) {
        if (source[field] !== undefined) next[field] = source[field];
      }
      if (JSON.stringify(next) !== JSON.stringify(row)) {
        writes.push(next);
        updated += 1;
      }
      continue;
    }

    const id = source.id ?? crypto.randomUUID();
    matched.add(id);
    writes.push({
      ...source,
      id,
      seedId: source.id,
      kind: source.kind ?? 'sentence',
      source: 'seed',
      createdAt: now,
    });
    added += 1;
  }

  const reviewed = new Set(reviews.map((r) => r.sentenceId));
  const dropped = existing
    .filter((row) => row.source === 'seed' && !matched.has(row.id) && !reviewed.has(row.id))
    .map((row) => row.id);

  await db.putMany(db.STORE.sentences, writes);
  await db.removeMany(db.STORE.sentences, dropped);
  return { added, updated, removed: dropped.length };
}

/**
 * Load everything the app ships with: translation cards and drills, which live
 * in two files and one store, and merge it. Never throws: a failed fetch is
 * just being offline.
 *
 * Two files because they are generated by different pipelines and reviewed
 * separately. One store because to the scheduler they are the same thing — a
 * row with an id, a Persian answer and a review history — and giving them
 * separate stores would mean two of every query.
 */
export async function loadBundled(
  url = 'data/seed_sentences.json',
  transformsUrl = 'data/transforms.json',
) {
  try {
    const [sentences, transforms] = await Promise.all([
      fetchRows(url, 'sentences'),
      fetchRows(transformsUrl, 'transforms'),
    ]);
    if (!sentences.length) return null;
    return await syncBundled([
      ...sentences,
      // kind is what promptFor and the session builder branch on. Set here
      // rather than in the file so an older bundle cannot arrive untagged.
      ...transforms.map((row) => ({ ...row, kind: 'transform' })),
    ]);
  } catch {
    return null;
  }
}

async function fetchRows(url, field) {
  try {
    const response = await fetch(url);
    if (!response.ok) return [];
    return (await response.json())[field] ?? [];
  } catch {
    // A missing transforms file is not a broken app — it is a deck without
    // drills in it.
    return [];
  }
}

// --- your own sentences -----------------------------------------------------
//
// A sentence you add is an ordinary row with source: 'custom'. That one field
// is what keeps it safe: syncBundled only ever prunes rows marked 'seed', and
// backup.js exports everything that is not 'seed' as customSentences. So your
// own material survives a deck update and travels with a backup, without
// either of those needing to know it exists.

/** Normalise for comparison: ZWNJ and spacing vary, meaning does not. */
function sameText(a, b) {
  const clean = (s) => (s || '').replace(/‌/g, '').replace(/\s+/g, ' ').trim();
  return clean(a) === clean(b);
}

export async function listCustom() {
  const all = await db.getAll(db.STORE.sentences);
  return all
    .filter((s) => s.source === 'custom')
    .sort((a, b) => (b.addedAt ?? 0) - (a.addedAt ?? 0));
}

/**
 * Add one pair. Returns the row, or throws with a reason the caller can show.
 *
 * Difficulty defaults to the learner's current level so the sentence enters
 * the rotation they are actually working through rather than sitting unseen
 * behind a gate.
 */
export async function addCustom({ english, farsi, finglish = '', difficulty = 1 }) {
  const englishText = (english || '').trim();
  const farsiText = (farsi || '').trim();
  if (!englishText || !farsiText) throw new Error('empty');
  if (!/[؀-ۿ]/.test(farsiText)) throw new Error('notPersian');

  const all = await db.getAll(db.STORE.sentences);
  if (all.some((s) => sameText(s.farsiText, farsiText))) throw new Error('duplicate');

  const row = {
    id: crypto.randomUUID(),
    englishText,
    farsiText,
    finglish: (finglish || '').trim(),
    literalGloss: '',
    difficulty,
    situation: 'expressing an opinion',
    grammarTags: [],
    kind: 'sentence',
    source: 'custom',
    addedAt: Date.now(),
  };
  await db.put(db.STORE.sentences, row);
  return row;
}

/** Remove a sentence you added, and any scheduling attached to it. */
export async function removeCustom(id) {
  const reviews = await db.getAll(db.STORE.reviews);
  await db.removeMany(db.STORE.reviews, reviews.filter((r) => r.sentenceId === id).map((r) => r.key));
  await db.remove(db.STORE.sentences, id);
}
